### ISSUE TITLE
How to access the man page?

### ISSUE THREAD

**Issue by antonioOrtiz** [ShaunLWM/node-compress-image-cli#2]
Hey thank you for making such an awesome tool! But haven't been able to get it to work?

I tried this:

```
compress -i /Users/antoniopavicevac-ortiz/Sites/jcb-image-optimization/src 

-o /Users/antoniopavicevac-ortiz/Sites/jcb-image-optimization/dist/images
```

Could you provide any insight?

Thanks so much!

**Comment by ShaunLWM** [comment]
I apologize that it wasn't working earlier due to the wrong command line usage in the `package.json` file. Library has been updated to 0.0.3. Please take a look and feel free to open a new issue if it still doesn't work. The README file has been updated with examples as well. Once again, I apologize and thank you.
